/// Flutter icons KacinvestIcon2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KacinvestIcon2
///      fonts:
///       - asset: fonts/KacinvestIcon2.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class KacinvestIcon2 {
  KacinvestIcon2._();

  static const _kFontFam = 'KacinvestIcon2';
  static const _kFontPkg = null;

  static const IconData chart_area = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_up = const IconData(0xf102, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData angle_double_down = const IconData(0xf103, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
