/// Flutter icons KacinvestIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KacinvestIcon
///      fonts:
///       - asset: fonts/KacinvestIcon.ttf
///
/// 
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class KacinvestIcon {
  KacinvestIcon._();

  static const _kFontFam = 'KacinvestIcon';

  static const IconData spin4 = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData arrow_up = IconData(0xe877, fontFamily: _kFontFam);
  static const IconData up_circled = IconData(0xf0aa, fontFamily: _kFontFam);
  static const IconData angle_double_up = IconData(0xf102, fontFamily: _kFontFam);
}
